INSERT INTO UF (descricao,sigla) VALUES ("Acre",                  "AC");
INSERT INTO UF (descricao,sigla) VALUES ("Alagoas",               "AL");
INSERT INTO UF (descricao,sigla) VALUES ("Amap",                  "AP");
INSERT INTO UF (descricao,sigla) VALUES ("Amazonas",              "AM");
INSERT INTO UF (descricao,sigla) VALUES ("Bahia",                 "BA");
INSERT INTO UF (descricao,sigla) VALUES ("Cear",                  "CE");
INSERT INTO UF (descricao,sigla) VALUES ("Distrito Federal",      "DF");
INSERT INTO UF (descricao,sigla) VALUES ("Gois",                  "GO");
INSERT INTO UF (descricao,sigla) VALUES ("Esprito Santo",         "ES");
INSERT INTO UF (descricao,sigla) VALUES ("Maranho",               "MA");
INSERT INTO UF (descricao,sigla) VALUES ("Mato Grosso",           "MT");
INSERT INTO UF (descricao,sigla) VALUES ("Mato Grosso do Sul",    "MS");
INSERT INTO UF (descricao,sigla) VALUES ("Minas Gerais",          "MG");
INSERT INTO UF (descricao,sigla) VALUES ("Par",                   "PA");
INSERT INTO UF (descricao,sigla) VALUES ("Paraiba",               "PB");
INSERT INTO UF (descricao,sigla) VALUES ("Paran",                 "PR");
INSERT INTO UF (descricao,sigla) VALUES ("Pernambuco",            "PE");
INSERT INTO UF (descricao,sigla) VALUES ("Piau",                  "PI");
INSERT INTO UF (descricao,sigla) VALUES ("Rio de Janeiro",        "RJ");
INSERT INTO UF (descricao,sigla) VALUES ("Rio Grande do Norte",   "RN");
INSERT INTO UF (descricao,sigla) VALUES ("Rio Grande do Sul",     "RS");
INSERT INTO UF (descricao,sigla) VALUES ("Rondnia",               "RO");
INSERT INTO UF (descricao,sigla) VALUES ("Rorima",                "RR");
INSERT INTO UF (descricao,sigla) VALUES ("So Paulo",              "SP");
INSERT INTO UF (descricao,sigla) VALUES ("Santa Catarina",        "SC");
INSERT INTO UF (descricao,sigla) VALUES ("Sergipe",               "SE");
INSERT INTO UF (descricao,sigla) VALUES ("Tocantins",             "TO");
